name: github pages

on:
  workflow_dispatch:
  pull_request:
  push:
    branches-ignore:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.7'
          architecture: 'x64'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip wheel
          python3 -m pip install -r ./requirements.txt

      - run: mkdocs build

      - name: Upload Results
        uses: actions/upload-artifact@v3
        with:
          name: website
          path: ./site

  deploy:
    runs-on: ubuntu-20.04
    needs: build
    concurrency: ci-${{ github.ref }}
    permissions:
      contents: write
    if: github.repository != 'msys2/msys2.github.io' || (github.event_name != 'pull_request' && github.ref == 'refs/heads/source')
    steps:
      - name: Download Results
        uses: actions/download-artifact@v3
        with:
          name: website
          path: ./site

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          publish_branch: master
          cname: www.msys2.org
